// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ6rWl8dls5Kk0qXfZfX2DmozKuEyLb98',
    appId: '1:996984033780:web:79af68720a6afccd4669a1',
    messagingSenderId: '996984033780',
    projectId: 'fir-final-36b5c',
    authDomain: 'fir-final-36b5c.firebaseapp.com',
    storageBucket: 'fir-final-36b5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUfjz4GqQmTP7Bv9ngUT1PxBn8s3lPFjk',
    appId: '1:996984033780:android:0654d57a3076e7894669a1',
    messagingSenderId: '996984033780',
    projectId: 'fir-final-36b5c',
    storageBucket: 'fir-final-36b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuoSOK2VZ_a6l-ckRYWFHN3eqTMlyA4Sw',
    appId: '1:996984033780:ios:929b890ed5df6d194669a1',
    messagingSenderId: '996984033780',
    projectId: 'fir-final-36b5c',
    storageBucket: 'fir-final-36b5c.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFinal',
  );
}
